### ISSUE TITLE
String class + PHP7

### ISSUE THREAD

**Issue by TomBZombie** [Level-2/Transphporm#10]
String is a keyword in PHP7 and this class is not allowed.

**Comment by smolinari** [comment]
Looking for what you meant (the class called String) and a bit off topic, but I like the locale stuff you added. :sunglasses: 

Scott

**Comment by TomBZombie** [comment]
Here: https://github.com/Level-2/Transphporm/blob/master/src/Formatter/String.php 

In PHP7 String is a keyword so you can't use it as a class name :)

**Comment by smolinari** [comment]
Yeah, I understood what the issue was ( I am following PHP7 fairly closely). I just went looking for the class called "String" to see what it was doing (and possibly come up with an idea on renaming the class). But, I don't know of a better name. Characters? CharVals (for character values)? Charseq (for character sequence)? Cord? Rope? LOL! 

Scott
