### ISSUE TITLE
Discussion: Javascript/AJAX methods

### ISSUE THREAD

**Issue by cxj** [Level-2/Transphporm#134]
I have some templates which have panels (<div>s) within which need to be dynamically updated on a periodic basis.  That's easy enough to do with a bit of Javascript (JS) and AJAX (XMLHttpRequest).  I can put that Javascript right in my XML template, but if I'm assembling my page from partials, maybe there's a better technique?

Ideally, I'd like to be able to animate my template with JS from the TSS file, and even better, I'd like to only include my JS AJAX library on pages which really need it.  The latter means I need to dynamically change the <script> tags on my "base" template on the fly, as well.

Are there "Transphporm intended" ways of doing this?

**Comment by TomBZombie** [comment]
In principle the javascript version of Transphporm ( https://github.com/Level-2/Tranjsform ) can help here because you can load the partial in the client. It's also reactive so:


```js

var template = new Tranjsform.Template(document, 'p { content: data(text); }');

var data = {text: 0 };

template.output(data);

setInterval(function() {
data.text++;
}, 5000);
```

This will run the tss on `document` (which can be the document loaded in browser) and you'll see the paragraph updated every 5 seconds.

I say *in priciple*  because it mostly works but I am in the process of re-writing Transjsform from scratch for Node.js based on the current release of Transphporm and then making it browser friendly.

Essentially, you'll need to use AJAX if you want to get data from the sever regardless of how you abstract it, but the question is really do you want to render the template on the server or on the client?

**Comment by cxj** [comment]
For my current application, I really do need to render the template on the server via PHP.  And this works perfectly for the vast majority of the application.  But I do need to use a bit of JS and AJAX here and there.

**Comment by TomBZombie** [comment]
can you give me an example of what you'd like to do? Obviously you're not going to be able to "animate my template with JS from the TSS file," if the template is being rendered on the server unless you include some javascript code in the template.

**Comment by TomBZombie** [comment]
I'm closing this as I'm still unsure what you're trying to achieve. Feel free to reopen and answer my question above. Even include some sample TSS/XML code and explain what you would like to happen.
