### ISSUE TITLE
Load template and parse TSS not working?

### ISSUE THREAD

**Issue by rdeelstra** [Level-2/Transphporm#166]
Hi,

This seems not to be working in the TSS file:
```
body:before {content:template("xml/default/default.xml");}
header {content: "Test";}
```

default.xml is loading but the rest is not being parsed.

Contents default.xml
```
<header role="banner"></header>
<nav id="nav-primary" role="navigation"></nav>
<main role="main"></main>
<footer></footer>
```

I would like to do something like this (to test also):
```
body:before {content:template("xml/default/default.xml");}
@import "header.tss";
```

Best regards, Rinnert

**Comment by rdeelstra** [comment]
Update, seems to be working in a way.
When I change default.xml to
```
<header role="banner">
    <span></span>
</header>
<nav id="nav-primary" role="navigation"></nav>
<main role="main">
    <span></span>
</main>
<footer></footer>
```

And the TSS to
```
body:before {content:template("xml/default/default.xml");}
header span {content: "Test";}
main span {content: "Test";}
```

Even this works without changing the default.xml:
```
body:before {content:template("xml/default/default.xml");}
header:before {content: "Test";}
main:before {content: "Test";}
```

But this isn't:
```
body:before {content:template("xml/default/default.xml");}
header {content: "Test";}
main {content: "Test";}
```

**Comment by solleer** [comment]
The reason is because Transphporm sorts the rules by how many parts are in them first so `header` is run before `body:before`

**Comment by garrettw** [comment]
For all Transphporm talks about its CSS-like syntax, I feel like following its lead in terms of source-order parsing would make things a lot more straight-forward to devs using this package.

**Comment by solleer** [comment]
@TomBZombie Should the sorting be removed and have it go purely off of source order?

**Comment by TomBZombie** [comment]
No, that causes all kind of problems when you have `@include` statements which need to be applied to the document.

CSS also does depth sorting.

```css
body footer { background-color: red; }
footer { background-color: green; }
```

This will give you a red background because the depth of the rule influences order.

The issue here is that `body:before` counts as two rules. I think the answer is that pseudo selectors should be omitted from the count for sorting purposes.

**Comment by garrettw** [comment]
Tangential question: does `::before` also work? Seeing as that's technically the correct syntax for pseudo-elements, and a single colon is more for pseudo-selectors, like `:hover` `:active` `:focus` etc.

**Comment by TomBZombie** [comment]
Yes, `::` and `:` are interchangeable, not through design but because of the way transphporm handles pseudo selectors. `div:::::::::::::::::::after` will also work. Unless we choose to make `::` and `:` act differently, it's probably not worth amending this behaviour.

**Comment by TomBZombie** [comment]
I've removed pseudo selectors form the count that's done for ordering purposes, it will avoid this issue. It should not affect anything else unless someone was relying on the old behaviour. I can't imagine there's too many cases where this would crop up though as it's only where `:before` or `:after` include another file (or otherwise create using `repeat`)  that would cause the order to make any difference.
