### ISSUE TITLE
Date tests fail

### ISSUE THREAD

**Issue by tontof** [Level-2/Transphporm#17]
I don't know why, maybe it's my configuration, but, your date tests fail :-(
I've just modified your src/Hook/BasicProperties.php file because of the splat operator because I'm using PHP 5.5.9 (but I don't think that's the reason)

FAILURES!
Tests: 68, Assertions: 68, Failures: 5.

For example:
```
1) DateFormatTest::testFormatDate
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'25/12/2014'
+'24/12/2014'
```

I did not add tests for frFR.json on my PR because of that.
Any idea ?

**Comment by TomBZombie** [comment]
This may be a timezone issue between your server time (likely Europe/Paris?) and the tests running under Europe/London. If you run the following code, does it give the expected result:


```php
$date = new \DateTime('2014-12-25');
$date->setTimeZone(new \DateTimeZone('Europe/London'));
echo $date->format('d/m/Y');
```

If that shows 24/12/2015, perhaps the tests will need to use the server timezone rather than reading it from the enGB locale for the tests.

**Comment by tontof** [comment]
```24/12/2014```
If I use ```date_default_timezone_set('Europe/London');``` before it returns
```25/12/2014```

**Comment by TomBZombie** [comment]
Is it still affected after this change: https://github.com/Level-2/Transphporm/commit/b7242423b01a9e598b6ad40f874a69b2fc4935fb ?

**Comment by tontof** [comment]
OK (69 tests, 69 assertions)
