### ISSUE TITLE
Template document parsing

### ISSUE THREAD

**Issue by garrettw** [Level-2/Transphporm#182]
I just ran across this library and wondered if it would be useful to you as an improvement over the current parsing setup.

https://github.com/ivopetkov/html5-dom-document-php

**Comment by TomBZombie** [comment]
Interesting. It's a fairly small wrapper and we fix a couple of the smaller issues in similar ways. It's probably not worth the overhead though as there's a lot of stuff we can't use, like CSS selectors. If we run into an issue that this would solve that can't be done easily otherwise I'll see if it's worth implementing.

The way that the `QuerySelector` class there is implemented is incredibly inefficient as well, it literally iterates over every element. I think the way we do it with XPath is considerably better!

**Comment by garrettw** [comment]
Ok, cool. I didn’t look into the code - just wanted to see if it would be useful or not.
