### ISSUE TITLE
Multi-dimensional data access notation

### ISSUE THREAD

**Issue by garrettw** [Level-2/Transphporm#194]
As [the wiki states](https://github.com/Level-2/Transphporm/wiki/Basic-Usage:-Working-with-external-data#data-structures), accessing array sub-elements and the like is done using dot notation.
My question is, is that the ideal notation to choose, given that it looks more like JavaScript than CSS or even PHP? I acknowledge that you probably thought through this in-depth when making the choice, so I'm curious to know how you decided on using a dot for this purpose.

**Comment by TomBZombie** [comment]
Since CSS doesn't support data structures, there's not really anything there to base it on.

Transphporm, like javascript, treats objects and arrays interchangeably so `data(foo.bar)` is the same as `data(foo[bar])`. 

It would have been possible to use (and is still possible to implement) PHP's `->` operator for `data(foo->bar)` but this causes additional parsing complexity when implementing subtract arithmetic or greater than comparisons.... and transphporm's original parser was very crude.

**Comment by garrettw** [comment]
I've never been a fan of PHP's `->`; it's too much effort to type. I also wouldn't be in favor of `array[element]` syntax given that the data in question could be an object, which would be confusing.
I thought of using CSS's child selector `>` for obvious reasons, but if determining the meaning of `>` would be difficult, would the descendant selector (a space) be any easier?

**Comment by cxj** [comment]
Staying with `.` and the array brackets `[]` _as is_ seems like the right thing to do, to me.  I've got arrays with element keys that contain spaces, e.g. `data(foo['the key'])` so changing would really give me trouble, I think.
