### ISSUE TITLE
Question: empty XML/HTML tags safe?

### ISSUE THREAD

**Issue by cxj** [Level-2/Transphporm#205]
This seems to work in all my test cases, but is it safe to depend on this behavior?  If I use an _empty_ or "collapsed" tag, Transphporm properly fills in the substitution value and closes the tag correctly.   That is, using `<span/>` instead of `<span></span>`.  
Example:
```php
$xml = '
<span id="foo"/>
<td/>
';
$tss = '
#foo {content: "The span content";}
td {content: "The table cell content.";}
';
```
Output:
```html
<span id="foo">The span content</span>
<td>The table cell content.</td>
```

**Comment by kip-13** [comment]
I think this behaviour is from [`DOMDocument`](http://php.net/manual/en/class.domdocument.php) tha is used in:

https://github.com/Level-2/Transphporm/blob/975e786beaf0144538c7cc12258d26748537fbfa/src/Template.php#L34-L55

You cant make a test:

```php
>>> $doc = new \DOMDocument()
>>> $doc->loadHTML('<span id="foo"/>')
>>> $doc->saveHTML()
=> """
   <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">\n
   <html><body><span id="foo"></span></body></html>\n
   """
>>>
```

**Comment by kip-13** [comment]
I think this behaviour is from [`DOMDocument`](http://php.net/manual/en/class.domdocument.php) used in:

https://github.com/Level-2/Transphporm/blob/975e786beaf0144538c7cc12258d26748537fbfa/src/Template.php#L34-L55

You can make a test:

```php
>>> $doc = new \DOMDocument()
>>> $doc->loadHTML('<span id="foo"/>')
>>> $doc->saveHTML()
=> """
   <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">\n
   <html><body><span id="foo"></span></body></html>\n
   """
>>>
```

You can read this comment from the docs:

> DOMDocument is very good at dealing with imperfect markup, but it throws warnings all over the place when it does. 
> This isn't well documented here. The solution to this is to implement a separate aparatus for dealing with just these errors. 
> Set libxml_use_internal_errors(true) before calling loadHTML. This will prevent errors from bubbling up to your default error handler. And you can then get at them (if you desire) using other libxml error functions. 
You can find more info here http://www.php.net/manual/en/ref.libxml.php

http://php.net/manual/en/domdocument.loadhtml.php#95463

**Comment by TomBZombie** [comment]
Yes, in theory it should be safe to rely on the behaviour. As @kip-13  suggests, it comes down to php's `DomDocument`.

Transphporm internally tracks whether the document should be treated as HTML or XML, for the most part it makes no difference, the only time it applies is when saving and loading. We have had issues in the past where using loadHTML and then saveXML have strange effects so, as in the code snippet in kip's post, if the transphorm is in XML mode it XML uses loadXML and saveXML, otherwise it falls back to loadHTML and saveHTML.

Unless you specify `<?xml version="1.0"?>` in your template, Transphporm will assume it's dealing with HTML. This was not the case in much earlier versions but there were issues caused when you loaded a HTML template into an existing XML template. It's better just to rely on HTML. unless you're using XML everywhere.

If you're using XML mode, transphporm expand empty tags because it's saved in `LIBXML_NOEMPTYTAG` mode. For HTML it will follow the the HTML specifications to decide which tags should/should not be empty.

I haven't tested this, but in theory <img></img> should be converted to <img> automatically. 

So going back to your question, the answer is *probably*. Though I would question the wisdom of using this behaviour on purpose given the principle of least surprise.

**Comment by cxj** [comment]
Thank you both for all of the information.  I don't intend to use this behavior, but discovered it worked through accident.
