### ISSUE TITLE
Option value with embedded space causes exception

### ISSUE THREAD

**Issue by cxj** [Level-2/Transphporm#221]
The following code causes Transphporm to throw an exception:
```php
<?php
require "vendor/autoload.php";

$xml = <<<XML
    <select>
        <option value="one">One</option>
        <option value="in two">Two</option>
        <option value="tre">Three</option>
    </select>
XML;

$tss = <<<TSS
option[value=data(option)]:attr(selected) {
    content: "selected";
}
TSS;

$data["option"] = "in two";

$template = new Transphporm\Builder($xml, $tss);
$output = $template->output($data)->body;
echo $output . PHP_EOL;
```

Here's the exception.  It appears some kind of quoting or escaping may be needed, given the syntax of TSS am unsure how that should be done.
```sh
PHP Fatal error:  Uncaught Exception:  `in` can only be used with arrays in /Users/chris/templates/vendor/level-2/transphporm/src/Parser/ValueResult.php:43
Stack trace:
#0 /Users/chris/templates/vendor/level-2/transphporm/src/Parser/ValueResult.php(39): Transphporm\Parser\ValueResult->in('two')
#1 /Users/chris/templates/vendor/level-2/transphporm/src/Parser/Last.php(74): Transphporm\Parser\ValueResult->processValue('two')
```

**Comment by TRPB** [comment]
The problem here is `$data["option"] = "in two";` 

When it reads `in two` it parses it (Which it shouldn't) but fixing this is actually rather difficult because it's tied into the root of the parsing code. At some point I want to rewrite the expression parser (used for things like `foo + bar` and `data(foo)=bar` as it's a bit of a mess. 

Unfortunately it's not a quick fix. For now, you'll need to remove the word "in" from both locations for this to work.

**Comment by TRPB** [comment]
Ignore the above post, I did manage to fix it. Having said that, the parser still needs a rewrite as it's difficult to work with at the moment.
