### ISSUE TITLE
Looping problems

### ISSUE THREAD

**Issue by nbish11** [Level-2/Transphporm#238]
Say I have this HTML partial:

```html
/* partial.html */

<ul>
  <li>One</li>
  <li>Two</li>
  <li>Three</li>
</ul>
```

And I pair it with this TSS:

```tss
/* main.tss */

ul > li {
  repeat: data();
  content: iteration();
}
```

I run this script:

```php
<?php
require_once 'vendor/autoload.php';

$template = new \Transphporm\Builder('partial.html', 'main.tss');
$data = [1,2,3];

echo $template->output($data)->body;
```

This is the output I get:

```html
<ul>
	<li>1</li><li>2</li><li>3</li>
	<li>1</li><li>2</li><li>3</li>
	<li>1</li><li>2</li><li>3</li>
</ul>
```

When, what I was expecting is this:

```html
<ul>
	<li>1</li><li>2</li><li>3</li>
</ul>
```

So, my question is, is this a bug or a feature? If I just put in one `<li>` element inside the `<ul>` tag, it works as expected, but the partials I get from the designer, usually have full lists in them, which I have to manually remove.

Note: I have tried using the `content-mode: replace;` property but end up with this output:

```html
<ul>
	1<li></li><li>
	1</li><li></li><li>
	1</li><li></li><li></li>
</ul>
```

**Comment by TRPB** [comment]
This is intentional, it will loop any element matched by the CSS selector (in the same way CSS would apply `color: red` to all `li` elements when you used `ul > li { color: red}`, Transphporm will apply `repeat` to each of the li elements and repeat it for all iterations.

To get the desired output you should only have one li element in the `<ul>` in the template. If you think about using PHP to generate it, you'd only have one `<li>` there as well:

```php
foreach ($list as $item) {
 echo '<li>' . $item . '</li>';
}
```

whereas:


```php
foreach ($list as $item) {
 echo '<li>' . $item . '</li>';
 echo '<li>' . $item . '</li>';
 echo '<li>' . $item . '</li>';
}
```

would give you duplicated list items as well.
