### ISSUE TITLE
Selector

### ISSUE THREAD

**Issue by solleer** [Level-2/Transphporm#33]
This does not work
```
select { bind: data(attr(name)); }
select option[value=data()]:attr(selected) { content: 'selected'; }
```

**Comment by TomBZombie** [comment]
I fixed several bugs yesterday in a commit, I've just pushed them and it seems to have fixed this too, see the latest unit test :)

**Comment by solleer** [comment]
I looked at the test. It still is not working. It appears to be working because when data() is called in the selector it just reads off the first value in the array which in this case is the same as what is being binded. In my code that has the same tss I have an object as the first thing in the array and I constantly get the error of it trying to convert it to a string when this tss is used.

**Comment by TomBZombie** [comment]
The test is passing, can you post the entire code including XML TSS and Data, also ensure you're using the latest commit as I did add several bug fixes.

**Comment by solleer** [comment]
tss
```
select { bind: data(attr(name)); }
select option[value=data()]:attr(selected) { content: 'selected'; }
```
xml
```
<select name='test'>
<option value='test1'>Test1</option>
<option value='test2'>Test2</option>
</select>
```

**Comment by TomBZombie** [comment]
This is the exact code from:

https://github.com/Level-2/Transphporm/commit/a9f8696435ccdcbf727e3f7bd56b0df2ff906fad

Is the test passing when you run phpunit?

**Comment by TomBZombie** [comment]
Never mind, I see the problem, if there are other entires in the data() array it doesn't produce the correct result.

**Comment by TomBZombie** [comment]
Having looked at it further, this is going to take quite a lot of work to fix because when the CSS e.g. `select option[value=data()]` is converted to `xpath` it happens before `bind: data(attr(name)` and to work out what data has been bound to an element it needs to happen before the xpath is generated. I'm looking at a solution using http://php.net/manual/en/domxpath.registerphpfunctions.php but it involves static methods.. which means keeping track of $data instances and which sheet they're associated with somehow.

**Comment by TomBZombie** [comment]
Try that, bit of a hacky workaround with statics. This shouldn't cause a problem as everything that relies on the global state is dealt with inside the $output method, so in theory there's no way for the global state to be changed while `output()` is running. This would be so much easier without needing to resort to statics, if anyone knows if there's something similar to http://php.net/manual/en/domxpath.registerphpfunctions.php whihc can take a callback instead of a static function name, let me know

**Comment by solleer** [comment]
That appears to work

**Comment by solleer** [comment]
could a :not() selector be added

**Comment by TomBZombie** [comment]
Can you give a use-case where this is useful/how you'd expect it to work?

**Comment by solleer** [comment]
If I have a calendar and all div's of events in each td have the class 'event' and one of the following classes: 'single-day' , 'first-day', 'last-day' , 'middle-day'
Only the 'single-day' and 'first-day' classes will have the event name
You would use this
```
div.event:not(.first-day,.last-day) { content: ''; }
```
It would work much like the :not() CSS selector

**Comment by solleer** [comment]
Also I noticed tss doesn't support separating selectors with commas
This would help avoid writing rules over and over again

**Comment by TomBZombie** [comment]
`:not` is quite a bit more complex but I've added support for separating selectors with commas

**Comment by TomBZombie** [comment]
I've added basic `:not` support, currently it should work with any selector with the exception of pseudo elements so fore example `:not(:first-child)` will not work but `:not(.foo)` will

**Comment by solleer** [comment]
Also it would be useful to chain `:attr()` and `:before/:after`
If you want to add on to a link you could use
```
#link:attr(href):after { content: 'id of something'; }
```

**Comment by TomBZombie** [comment]
Yeah, I was about to post that alternative although :before and :after might be more intuitive
