### ISSUE TITLE
No error message when .tss file not found

### ISSUE THREAD

**Issue by Pixelfck** [Level-2/Transphporm#69]
**version:** dev-master, 1.0.0

Observed behaviour
--------------------------

When I try to:

~~~ php
<?php
use Transphporm\Builder AS TransphpormBuilder;

$transphporm = new TransphpormBuilder('index.xml', 'NON_EXISTING_TSS_FILE');
echo $transphporm->output($this->data)->body;		
~~~

I do not see any error message.

Expected behaviour
-------------------------
Some message indicating there is an error

**Comment by TomBZombie** [comment]
Because the second argument can be either a tss file or a string of rules, in this case, it will be interpreted as rules. There should be some kind of error, but here it would have to be "No TSS rules parsed" or similar because it first checks to see whether the arugment is a file, and then parses the TSS.

**Comment by Pixelfck** [comment]
"No TSS rules parsed" would work just fine :-)
