### ISSUE TITLE
CssToXpath attr selector bug

### ISSUE THREAD

**Issue by solleer** [Level-2/Transphporm#95]
Since the value parser is decoupled from the element now, the functionset must be passed all the way to CssToXpath for it to work

**Comment by solleer** [comment]
This test fails
```php
public function testSelectAttributeFromData2AndOtherFunctionUsedBefore() {
		$data = ['model' => ["cal_links" => ['month' => 6]]];

		$includeFile = __DIR__ . DIRECTORY_SEPARATOR . 'calendar.xml';
		$includeFile = str_replace('\\', '/', $includeFile);

		$tss = "main { content: template('$includeFile'); bind: data(model); }


		#month option[value=data(cal_links.month)]:attr(selected) { content: 'selected'; }";


		$xml = '<main></main>';

		$template = new \Transphporm\Builder($xml, $tss);

		$output = $template->output($data)->body;

		$this->assertEquals($this->stripTabs('
<main><select name="month" id="month">
  <option value="1">January</option>
  <option value="2">February</option>
  <option value="3">March</option>
  <option value="4">April</option>
  <option value="5">May</option>
  <option value="6" selected="selected">June</option>
  <option value="7">July</option>
  <option value="8">August</option>
  <option value="9">September</option>
  <option value="10">October</option>
  <option value="11">November</option>
  <option value="12">December</option>
</select></main>'), $this->stripTabs($output));
	}
```
calendar.xml
```xml
<select name="month" id="month">
  <option value="1">January</option>
  <option value="2">February</option>
  <option value="3">March</option>
  <option value="4">April</option>
  <option value="5">May</option>
  <option value="6">June</option>
  <option value="7">July</option>
  <option value="8">August</option>
  <option value="9">September</option>
  <option value="10">October</option>
  <option value="11">November</option>
  <option value="12">December</option>
</select>
```

**Comment by solleer** [comment]
I can't think of a good way to get the functionset to the CssToXpath

**Comment by TomBZombie** [comment]
Yes, you're right. We need a test for this in the main set of tests.

I was trying to make the `Value` class easier to isolate by removing its dependency on a HTML element for some operations, however, perhaps this is the simpler solution.

The alternatives are giving `CssToXpath` a dependency on `FunctionSet` then either

- Give `Sheet` a dependency on `FunctionSet` and just to pass it through to `CssToXpath`.
- Or create  `CssToXpath` in `Builder` and pass it into `Sheet`  (this is undoubtedly the purest solution but would mean rewriting it so that the constructor doesn't take `$selector`)

I think the second is better, but it will mean passing `CssToXpath` as a dependency everywhere it's currently used.

**Comment by solleer** [comment]
The second option seems good. Though it will have to be passed around, that will avoid it being constructed so often.

**Comment by TomBZombie** [comment]
I've just done the above. I've also tidied up the `Builder` class quite a lot. Instead of passing every instance around, I've moved things to the `Config` class which acts like a primitive service locator.

**Comment by solleer** [comment]
A bunch of locations still try to pass the element to the parser still
